<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL (기본 사이트 URL)
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
| CodeIgniter의 root URL을 지정해주세요. 슬래시(/)를 포함해서 base URL로
| 사용됩니다:
|
|	http://example.com/
|
| 지정되지 않은 경우 설치 경로, 도메인 및 프로토콜이 자동으로 선택됩니다.
|
*/
$config['base_url'] = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
$config['base_url'] .= "://" . $_SERVER['HTTP_HOST'];
$config['base_url'] .= str_replace(basename($_SERVER['SCRIPT_NAME']), "", $_SERVER['SCRIPT_NAME']);


/*
|--------------------------------------------------------------------------
| Index File (Index 파일)
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
| 
| 파일 명을 변경하는 등의 특수한 경우를 제외하고 일반적으로 index.php 파일을 
| 지정합니다. 만약 mod_rewrite 모듈을 사용하지 않는다면 빈칸으로 두십시오.
|
*/
//$config['index_page'] = 'index.php';
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL (URI 프로토콜)
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
| URI 문자열로써 사용 될 Global 변수를 지정합니다. 기본 설정인 'AUTO'는
| 대부분의 서버에서 정상적동합니다. 제대로 동작하지 않는다고 판단되면
| 선호에 맞게 변경해줍니다.
|
| 'AUTO'			기본 - 자동 감지
| 'PATH_INFO'		PATH_INFO 사용
| 'QUERY_STRING'	QUERY_STRING 사용
| 'REQUEST_URI'		REQUEST_URI 사용
| 'ORIG_PATH_INFO'	ORIG_PATH_INFO 사용
|
*/
$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix (URL 접미어)
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
|
| CodeIgniter를 통해 생성되는 모든 URL에 접미사를 추가하는 옵션입니다.
| 자세한 정보는 사용자 가이드를 참조하세요:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language (기본 언어)
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
| 사용 될 언어 셋을 지정합니다. 영어 이외에 언어를 사용하실 경우에 사용
| 가능한 언어 셋이 있는지 반드시 확인해야 합니다.
|
*/
$config['language']	= 'korean';

/*
|--------------------------------------------------------------------------
| Default Character Set (기본 문자 셋)
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| 기본적으로 사용 될 문자 셋을 지정합니다.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks (시스템 훅 사용 설정/해제)
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
| '훅'을 사용 할 경우 TRUE로 세팅해주세요. 자세한 정보는 사용자 가이드를 
| 참조하세요.
|
*/
$config['enable_hooks'] = TRUE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix (클래스 확장 접두어)
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
| 네이티브 라이브러리를 확장 할 경우에 파일이름과 클래스 이름에 들어 갈 
| 접두어를 설정합니다. 자세한 정보는 사용자 가이드를 참조하세요:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters (URL 문자 허용)
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
| URL에 허용 될 문자를 정규표현식으로 지정합니다.
| 사용자가 허용되지 않은 문자가 포함 된 URL을 전송할 경우, 경고메시지를 출력합니다.
|
| 보안 향상을 위해 최소한의 문자만을 허용하는 것을 강력히 권고합니다.
| 기본값은 다음과 같습니다: a-z 0-9~%.:_-
|
| 값을 비워두면 모든 문자를 허용합니다 -- 절대로 해서는 안됩니다.
|
| 시스템에 어떤 영향을 끼치는지 완벽히 이해하지 못했다면 변경하지 마십시오.
|
*/
//$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';
$config['permitted_uri_chars'] = '가-힣a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings (쿼리 스트링 사용)
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
| CodeIgniter는 검색엔진 최적화를 위해 세그먼트 기반의 URL을 사용합니다:
| example.com/who/what/where/
|
| 기본적으로 $_GET 배열에 접근할 수 있습니다. 특정한 이유로 $_GET 배열에 
| 접근을 막기 위해서는 'allow_get_array'를 FALSE로 설정하세요.
|
| 원하는 경우 기본 쿼리 스트링 기반 URL을 사용할 수도 있습니다:
| example.com?who=me&what=something&where=here
|
| 옵션 값: TRUE 혹은 FALSE (boolean)
|
| 나머지 설정은 컨트롤러와 함수를 요청할 때 사용되어 질 쿼리 스트링의 
| 문자열을 지정합니다:
| example.com/index.php?c=controller&m=function
|
| CodeIgniter는 세그먼트 기반 URL로 제작되어졌기 때문에 이 기능을 사용할 시 
| 문제가 발생할 수도 있습니다.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold (에러 로그 기준)
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
| 에러 로그 기록 활성화 시, 기준을 설정합니다.
| 0 이상의 숫자를 사용해서 기준을 설정할 수 있습니다:
|
|	0 = 로그 기록하지 않음
|	1 = 에러 메시지 (PHP 에러 포함)
|	2 = 디버그 메시지
|	3 = 정보성 메시지
|	4 = 모든 메시지
|
| 사이트 활성화 시 속도를 위해 에러 메시지(1)만 기록하는 것이 좋습니다.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path (에러 로그 디렉토리 경로)
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
| 빈 값을 설정하면 기본 경로(application/logs/)에 기록합니다. 슬래시를 포함 한 
| 서버 경로를 입력하세요.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs (로그 날짜 포멧)
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
| 로그 기록에 사용 될 날짜 포멧으로, PHP의 date 코드를 사용해서 포멧을 지정
| 할 수 있습니다.
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path (캐시 디렉토리 경로)
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
| 빈 값을 설정하면 기본 경로(system/cache/)에 기록합니다. 슬래시를 포함 한
| 서버 경로를 입력하세요.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key (암호 키)
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
| 암호 클래스 혹은 세션 클래스를 사용하는 경우 반드시 암호 키를 설정해야 합
| 니다. 자세한 정보는 사용자 가이드를 참조하세요.
|
*/
$config['encryption_key'] = str_replace('.','_',$_SERVER['HTTP_HOST']).'_encryption_key';

/*
|--------------------------------------------------------------------------
| Session Variables (세션 변수)
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
| 'sess_cookie_name'		= 쿠키 이름을 설정합니다.
| 'sess_expiration'			= 세션 종료 시간을 초 기준으로 입력하세요. 기본 값은 7200초(2시간)
|  입니다. 0으로 설정하면 종료하지 않습니다.
| 'sess_expire_on_close'	= 브라우저 창이 닫힐 때 세션을 종료할 지 설정합니다.
| 'sess_encrypt_cookie'		= 쿠키를 암호화할 지 설정합니다.
| 'sess_use_database'		= 세션을 데이터베이스에 저장할 지 설정합니다.
| 'sess_table_name'			= 세션 데이터베이스 테이블 이름을 설정합니다.
| 'sess_match_ip'			= 세션 데이터를 읽을 때 사용자의 IP를 비교할 지 설정합니다.
| 'sess_match_useragent'	= 세션 데이터를 읽을 때 사용자 에이전트를 비교할 지 설정합니다.
| 'sess_time_to_update'		= CI가 세션 정보를 얼마나 자주 새로고침 할 지 초로 지정합니다.
|
*/
$config['sess_cookie_name']		= str_replace('.','_',$_SERVER['HTTP_HOST']).'_session';
$config['sess_expiration']		= 7200;
$config['sess_expire_on_close']	= FALSE;
$config['sess_encrypt_cookie']	= TRUE;
$config['sess_use_database']	= TRUE;
$config['sess_table_name']		= 'Sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= FALSE;
$config['sess_time_to_update']	= 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables (쿠키 관련 변수)
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
| 'cookie_prefix' = 충돌을 피하기 위해 접두어를 설정합니다.
| 'cookie_domain' = 사이트 전체에 쿠키를 적용하기 위해 .your-domain.com으로
|  설정할 수 있습니다.
| 'cookie_path'   =  일반적으로 슬래시(/)로 포워드합니다.
| 'cookie_secure' =  보안 HTTPS 연결만 사용할 경우 TRUE로 설정합니다.
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering (전역 XSS 필터링)
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = str_replace('.','_',$_SERVER['HTTP_HOST']).'_csrf_token_name';
$config['csrf_cookie_name'] = str_replace('.','_',$_SERVER['HTTP_HOST']).'_csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'GMT+9';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';


/* End of file config.php */
/* Location: ./application/config/config.php */
